src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $first_name;

    /**
     * @ORM\Column(type="date")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getAge(): ?\DateTimeInterface
    {
        return $this->age;
    }

    public function setAge(\DateTimeInterface $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }
    
    public function __toString(){
        // to show the name of the Category in the select
        return $this->name;
        // to show the id of the Category in the select
        // return $this->id;
    }
 

}

src/Controller/CountryPageController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Country;
use App\Entity\Publication;
use App\Form\PublicationType;
use App\Controller\BaseController;
use Doctrine\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use App\DataFixtures\PublicationFixtures;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CountryPageController extends AbstractController
{
    /**
     * @Route("/country/page/{id}", name="country_page")
     */
    public function index(Request $request, $id, EntityManagerInterface $entityManager){
        //récupération des données
        $repo = $this->getDoctrine()->getRepository(Country::class);
        $countrys = $repo->findAll();
        $user = $this->getUser();
        $country = $repo->find($id);
        $publications = $this->getDoctrine()->getManager()->getRepository(Publication::class)->findAll();
        
       //création du formulaire 
        $publication = new Publication();
        

        return $this->render('country_page/index.html.twig', [
            'country' => $country,
            'publications' => $publications,
            'countrys' => $countrys,
            'user' => $user,
            'publication' => $publication
        ]);
    }
  



}
   

templates/country_page/index.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ country.countryName }}{% endblock %}
  
{% block stylesheets %}

            
{% endblock %}
{% block body %}

{% if country.imagePays == "" %}
<main>
  <div id="bgPays" class="text-center">
    <h1 id="sloganPaysAlt" class="mb-4">{{ country.countryName }}</h1>
    <h2 id="sloganPaysAlt">C'est le moment de partir à l'aventure !</h2>
  </div>
</main>
{% else %}
<main id="imagePays" style='background-image:url("{{asset('img/pays/' ~ country.imagePays)}}")'>
    <h1 id="sloganPays" class="mb-4">{{ country.countryName }}</h1>
    <h2 id="sloganPays">C'est le moment de partir à l'aventure !</h2>
</main>
<div class="container">
<h2 class="mt-4 mb-4">À propos du pays</h2>
<p>{{ country.description }}</p>
</div>
{% endif %}

<h4 class="text-center" styles="color:#0d9b9c; font-family: 'calistoga'; margin-top: 5em;">Trouvez-vous un partenaire de voyage !</h4>
{% if user %}

<div class="box-article">         
<article class="m-auto flex-nowrap" id="sizeOfArticles">
  {% for publication in publications %}

  {% if country.countryCode == publication.countryName  %}
<div class="ml-1">
  <div class="card">
    <div class="presentation p-2 align-items-center">

      <div class="user-info d-flex" styles="height:3em;">
        <a href="{{ path('profil_voyageur',{'id':publication.user.id } ) }}"><img src="{{asset('img/profil/' ~ publication.user.img)}}" alt="pdp" class="profil-img ml-2" width="60px" height="60px"></a>
        <h3 class="m-3">{{ publication.user.firstName }}</h3>
      </div>

      <div class="date mt-3 pl-4">
        <h6>{{ publication.countryStart | country_name }}<i class="fas fa-plane m-2"></i> {{ publication.countryName | country_name }} </h6>
        <h7>{{ publication.date | date('d/m/Y')}}</h7>
      </div>
    </div>
    <div class="mt-auto mb-4">
      <a href="{{ path('profil_voyageur',{'id':publication.user.id } ) }}" class="button-info-1 m-1">A propos de {{ publication.user.firstName }}</a>
    </div>
  </div>  
</div>
  {% endif %}
{% endfor %}
</article>
</div>         
          


{% else %}
<div class="container-fluid text-center">
  <h4 class="mb-5 mt-5">Vous devez être connecté pour acceder à ce contenu</h2>
  <a class="login" href="{{ path('app_login') }}">Connexion</a>  
</div>
{% endif %}
</body>
{% endblock %}